### PR TITLE
Use test matrix

### PR DESCRIPTION
**Pull request by armandfardeau**
Hi Ivan, 

I noticed you use quite the same test files in 0.23 and 0.24, since you are using appraisal, I thought it could be simpler to use a test matrix and get rid of the complexity of the situation.

### CODE REVIEW

**Comment by microstudi** [comment]
Thanks @armandfardeau . Could you update the Readme badges then?

**Comment by armandfardeau** [comment]
Yes sure!

**Review by microstudi — APPROVED** [review]
Thanks! let's wait for the tests to pass and let's merge this

**Comment by armandfardeau** [comment]
> Thanks! let's wait for the tests to pass and let's merge this

Let me know if you need anything 🙂

**Pull request merged**
