### PR TITLE
Upgrade to Decidim 0.25

### PR DESCRIPTION
**Pull request by entantoencuanto**
WIP to upgrade to a version compatible with Decidim 0.25

Checklist:
- [ ] Check the necessity of the SassC gem (removed in decidim). used to check the validity of css in custom styles.
- [x] Refactor tests & appraisal (limit compatibility to 0.25)
- [x] Changelog & readme
- [x] bump version 0.8
- [x] Admin: constraint editor
- [x] custom styles
- [x] custom fields
- [x] custom fields with quill editor
- [x] admin custom fields
- [x] admin custom fields with quill editor
- [x] custom fields when data comes from POST (admin)
- [x] awesome maps
- [x] fullscreen iframe
- [x] scoped admins (select2)
- [x] editor override admin
- [x] editor override public
- [x] markdown editor admin
- [x] mardkown editor public
- [x] upload images to quill
- [x] upload images to textarea
- [x] upload images to markdown
- [x] focus tabs renders markdown
- [x] menu tweaks
- [x] intergram chat
- [x] autosave forms
- [x] system checker (md5)
- [x] remove old javascripts
- [x] remove old vendor
- [x] Remove CSS themes
- [x] Awesome map as a content block
- [x] Tests
- [ ] Image migrations (rake) and instructions

### CODE REVIEW

**Comment by entantoencuanto** [comment]
Hi, @microstudi, We've been working on the upgrade and we are able now to run the tests locally. For the moment there are some failing, the main problems we're dealing with are:

* Some js files require jquery-ui (specially app/packs/src/decidim/decidim_awesome/admin/form_builder.js, a sortable method is expected by formBuilder) but if we import it an error happens exposes-loader. It's a bit tricky error, we're working on it.
* The system compatibility is failing. Does it make sense to mantain or adapt it to support only a Decidim version or we can remove this part?
* The editor images feature doesn't work for the moment, the editor doesn't show the attach image option I think it has some relation with the js dependencies issues
* The themes feature is also failing currently

I'm currently working on replacing vendor js files with dependencies in packages.json

**Comment by microstudi** [comment]
The system compatibility is just a md5 checksum checker. I'll change that part if you want. It is useful to see if a overridden file has changed in the new version of Decidim so we need to look carefully to create a new overridden file with all the changes (both Decidim and the plugin). And yes, this time we will be compatible only with 0.25 (however in the future I'd like to maintain 2 version compatibility). This is going to be v0.8 for awesome. Future v0.9 should be compatible with 0.25 and 0.26.

 Thanks a lot for you hard work, I'll start digging into this probably next week.

**Comment by entantoencuanto** [comment]
Hi, we're stuck trying to get some of the javascripts to work :sweat: Take a look for example to the last commit. It seems that the submit event listener in app/packs/src/decidim/decidim_awesome/admin/form_builder.js doesn't work if `decidim_form_for` is used in app/views/decidim/decidim_awesome/admin/config/show.html.erb because there is a `data-abide` attribute introduced by the Decidim helper that if it's present no submit is captured. I can't figure out why

**Comment by microstudi** [comment]
@entantoencuanto, I think I've been able to unlock the javascript mess.
This is what I've found out:
- Importing external libraries in several `javascript_pack_tag` doesn't work very well. It seems that webpack/rails cannot keep track of what libraries are already called and then they repeat. This was happening specially for jquery, but also for formbuilder.

- The only solution that made the trick is to avoid calling the original pack from "decidim-admin" and include it instead in the entrypoint.
https://github.com/Platoniq/decidim-module-decidim_awesome/blob/2f9124f9c3f87f072bc625f15e693305c016ddf0/app/views/v0.25/layouts/decidim/admin/_header.html.erb#L1-L8
https://github.com/Platoniq/decidim-module-decidim_awesome/blob/2f9124f9c3f87f072bc625f15e693305c016ddf0/app/packs/src/decidim/decidim_awesome/awesome_admin.js#L3

- we need to be careful about including non-needed javascript/css (we cannot treat the entrypoint as we use when using sprockets manifests). All entrypoint code is included and that is not always desirable. On the other hand, due the problem of repeating dependencies, I think we need to include all the libraries that have dependencies (ie jquery). Selectively include code making use of these libraries when needed.

- I've found that we don't need a `custom.js` file either. 

I've updated the description with checkboxes (feel free to update it) to keep track of what is working and what not.

I'll continue next week. Would you be willing to start a slack channel or similar to further discussions? I'd invite you
Thanks!

**Comment by entantoencuanto** [comment]
That sounds pretty good, congratulations! Yes, invite me to a channel if the conversation can be more fluid

**Pull request merged**
